---
- name: Install packages
  ansible.builtin.pip:
    name:
      # - devpi-server=={{ devpi_version }}
      - devpi-client
      - devpi-web
      - wheel
      - setuptools
    state: present

- name: Initialize devpi
  ansible.builtin.shell: '/usr/local/bin/devpi-init \
    --serverdir /mnt/data/devpi/'
  ignore_errors: true

- name: Create the devpi directory
  ansible.builtin.file:
    path: /mnt/data/devpi
    state: directory
    mode: '0755'

- name: Add the systemd file for devpi
  become: true
  template:
    src: devpi.service
    dest: /etc/systemd/system/devpi.service
  notify:
    - restart devpi

- name: Add the devpi binaries to the bash path
  become: true
  template:
    src: devpi_path.sh
    dest: /etc/profile.d/devpi_path.sh
