---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: "Include rezizter.ansible_devpi"
      ansible.builtin.include_role:
        name: "rezizter.ansible_devpi"
