---
- name: Converge
  hosts: all
  tasks:
    - name: Install packages
      yum:
        name:
          - python3
  tasks:
    - name: "Include role"
      ansible.builtin.include_role:
        name: "rezizter.ansible_devpi"
