---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubuntu
    image: ubuntu:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
