---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazonlinux2023
    image: amazonlinux:2023
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
