---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux-9
    image: almalinux:9
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
