---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux-8
    image: almalinux:8
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
